GCC=g++
GCCFLAGS=-Wall -g -pedantic --std=c++11

# PLEASE ADD THE NAME OF ALL THE FILES YOU WANT TO GET ARCHIVED
UTIL_FILES=$(UTIL_LOC)/util.mk  \
	$(UTIL_LOC)/util.hpp $(UTIL_LOC)/util.cpp \
	$(UTIL_LOC)/timer.hpp \
	$(UTIL_LOC)/word-list.txt \
	$(UTIL_LOC)/README.txt\
	$(UTIL_LOC)/random-word-generator-demo.cpp

# all the object files generated by this module
UTIL_OBJS=$(OUT_LOC)/util.o \
	$(OUT_LOC)/random-word-generator-demo.o \
	$(OUT_LOC)/random-word-generator-demo


.PHONY: all clean

util-all: install
	@echo "generated executables"

util-install: init build
	$(GCC) $(GCCFLAGS) -o $(OUT_LOC)/random-word-generator-demo  \
		$(OUT_LOC)/random-word-generator-demo.o
	cp $(UTIL_LOC)/word-list.txt $(OUT_LOC)

util-build: init util random-word-generator-demo
	@echo "Please use - make install - to generate executables"

util: init
	$(GCC) $(GCCFLAGS) -c $(UTIL_LOC)/util.cpp -o $(OUT_LOC)/util.o

random-word-generator-demo: init
	$(GCC) $(GCCFLAGS) -c $(UTIL_LOC)/random-word-generator-demo.cpp -o $(OUT_LOC)/random-word-generator-demo.o

util-clean:
	rm -rf $(UTIL_OBJS)
